[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:pl"]

[start]
cmd = "cd packages/site-pl && pnpm preview --host 0.0.0.0 --port 3000"
